### ISSUE TITLE
name 'spm' is not defined

### ISSUE THREAD

**Issue by DerekBin** [Separius/BERT-keras#2]
Traceback (most recent call last):
  File "tutorial.py", line 6, in <module>
    model_name='tutorial', vocab_size=20)
  File "/media/bin_lab/C4F6073207B3A949/Linux/Bert/BERT-keras-master/data/vocab.py", line 59, in __init__
    spm.SentencePieceTrainer.Train(
NameError: name 'spm' is not defined

**Comment by Separius** [comment]
oh, I should have created a requirements file
in order to use sentencepiece encoder you need sentencepiece package
you can install it with:
```pip install sentencepiece```
